from datetime import date, datetime

from sqlalchemy import Boolean, Date, DateTime, Float, Integer, String
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base


class DadosClientes(Base):
    __tablename__ = "dados_clientes"

    id_cliente: Mapped[str] = mapped_column(String, primary_key=True)
    uf: Mapped[str | None] = mapped_column(String)
    faixa_etaria: Mapped[str | None] = mapped_column(String)
    canal_aquisicao: Mapped[str | None] = mapped_column(String)
    tier_clube: Mapped[str | None] = mapped_column(String)
    optin_email: Mapped[bool | None] = mapped_column(Boolean)
    data_cadastro: Mapped[date | None] = mapped_column(Date)
    dias_desde_cadastro: Mapped[int | None] = mapped_column(Integer)
    quantidade_pedidos: Mapped[int] = mapped_column(Integer, nullable=False)
    data_primeiro_pedido: Mapped[date | None] = mapped_column(Date)
    data_ultimo_pedido: Mapped[date | None] = mapped_column(Date)
    dias_desde_ultimo_pedido: Mapped[int] = mapped_column(Integer, nullable=False)
    intervalo_medio_pedidos: Mapped[float] = mapped_column(Float, nullable=False)
    intervalo_mediano_pedidos: Mapped[float] = mapped_column(Float, nullable=False)
    intervalo_minimo_pedidos: Mapped[int] = mapped_column(Integer, nullable=False)
    intervalo_maximo_pedidos: Mapped[int] = mapped_column(Integer, nullable=False)
    desvio_intervalo_pedidos: Mapped[float] = mapped_column(Float, nullable=False)
    quantidade_itens: Mapped[int] = mapped_column(Integer, nullable=False)
    quantidade_skus_distintos: Mapped[int] = mapped_column(Integer, nullable=False)
    quantidade_categorias_distintas: Mapped[int] = mapped_column(Integer, nullable=False)
    valor_total_compras: Mapped[float] = mapped_column(Float, nullable=False)
    ticket_medio: Mapped[float] = mapped_column(Float, nullable=False)
    ticket_mediano: Mapped[float] = mapped_column(Float, nullable=False)
    desconto_total: Mapped[float] = mapped_column(Float, nullable=False)
    percentual_pedidos_com_desconto: Mapped[float] = mapped_column(Float, nullable=False)
    percentual_pedidos_com_cupom: Mapped[float] = mapped_column(Float, nullable=False)
    itens_por_pedido: Mapped[float] = mapped_column(Float, nullable=False)
    margem_media: Mapped[float] = mapped_column(Float, nullable=False)
    quantidade_pedidos_com_cupom: Mapped[int] = mapped_column(Integer, nullable=False)
    prazo_medio_entrega: Mapped[float] = mapped_column(Float, nullable=False)
    atraso_medio_entrega: Mapped[float] = mapped_column(Float, nullable=False)
    maior_atraso_entrega: Mapped[float] = mapped_column(Float, nullable=False)
    pedidos_com_atraso: Mapped[int] = mapped_column(Integer, nullable=False)
    percentual_pedidos_com_atraso: Mapped[float] = mapped_column(Float, nullable=False)
    possui_interacao: Mapped[bool] = mapped_column(Boolean, nullable=False)
    meses_com_interacao: Mapped[int] = mapped_column(Integer, nullable=False)
    campanhas_enviadas_total: Mapped[int] = mapped_column(Integer, nullable=False)
    campanhas_reativacao_total: Mapped[int] = mapped_column(Integer, nullable=False)
    campanhas_abertas_total: Mapped[int] = mapped_column(Integer, nullable=False)
    cliques_total: Mapped[int] = mapped_column(Integer, nullable=False)
    sessoes_total: Mapped[int] = mapped_column(Integer, nullable=False)
    carrinhos_abandonados_total: Mapped[int] = mapped_column(Integer, nullable=False)
    tickets_sac_total: Mapped[int] = mapped_column(Integer, nullable=False)
    tickets_resolvidos_total: Mapped[int] = mapped_column(Integer, nullable=False)
    taxa_abertura_campanhas: Mapped[float] = mapped_column(Float, nullable=False)
    taxa_clique_campanhas: Mapped[float] = mapped_column(Float, nullable=False)
    taxa_resolucao_sac: Mapped[float] = mapped_column(Float, nullable=False)
    campanhas_reativacao_por_campanha: Mapped[float] = mapped_column(Float, nullable=False)
    cliques_por_campanha_aberta: Mapped[float] = mapped_column(Float, nullable=False)
    sessoes_por_pedido: Mapped[float] = mapped_column(Float, nullable=False)
    tickets_por_pedido: Mapped[float] = mapped_column(Float, nullable=False)
    carrinhos_por_sessao: Mapped[float] = mapped_column(Float, nullable=False)
    sem_interacao: Mapped[bool] = mapped_column(Boolean, nullable=False)
    data_referencia: Mapped[date] = mapped_column(Date, nullable=False)
    versao_atributos: Mapped[str] = mapped_column(String, nullable=False)
    gerado_em: Mapped[datetime] = mapped_column(DateTime, nullable=False)


class ClustersClientes(Base):
    __tablename__ = "clusters_clientes"

    id_cliente: Mapped[str] = mapped_column(String, primary_key=True)
    cluster: Mapped[int] = mapped_column(Integer, nullable=False)
    algoritmo: Mapped[str] = mapped_column(String, nullable=False)
    quantidade_clusters: Mapped[int] = mapped_column(Integer, nullable=False)
    data_referencia: Mapped[date] = mapped_column(Date, nullable=False)
    data_geracao: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    versao_atributos: Mapped[str] = mapped_column(String, nullable=False)
    silhouette_score: Mapped[float] = mapped_column(Float, nullable=False)
    conjunto_variaveis: Mapped[str] = mapped_column(String, nullable=False)


class ResultadosCluster(Base):
    __tablename__ = "resultados_cluster"

    cluster: Mapped[int] = mapped_column(Integer, primary_key=True)
    quantidade_clientes: Mapped[int] = mapped_column(Integer, nullable=False)
    quantidade_clusters: Mapped[int] = mapped_column(Integer, nullable=False)
    data_referencia: Mapped[date] = mapped_column(Date, nullable=False)
    data_geracao: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    versao_atributos: Mapped[str] = mapped_column(String, nullable=False)
    silhouette_score: Mapped[float] = mapped_column(Float, nullable=False)
    dias_desde_cadastro: Mapped[float] = mapped_column(Float, nullable=False)
    quantidade_pedidos: Mapped[float] = mapped_column(Float, nullable=False)
    dias_desde_ultimo_pedido: Mapped[float] = mapped_column(Float, nullable=False)
    intervalo_medio_pedidos: Mapped[float] = mapped_column(Float, nullable=False)
    intervalo_mediano_pedidos: Mapped[float] = mapped_column(Float, nullable=False)
    intervalo_minimo_pedidos: Mapped[float] = mapped_column(Float, nullable=False)
    intervalo_maximo_pedidos: Mapped[float] = mapped_column(Float, nullable=False)
    desvio_intervalo_pedidos: Mapped[float] = mapped_column(Float, nullable=False)
    quantidade_itens: Mapped[float] = mapped_column(Float, nullable=False)
    quantidade_skus_distintos: Mapped[float] = mapped_column(Float, nullable=False)
    quantidade_categorias_distintas: Mapped[float] = mapped_column(Float, nullable=False)
    valor_total_compras: Mapped[float] = mapped_column(Float, nullable=False)
    ticket_medio: Mapped[float] = mapped_column(Float, nullable=False)
    ticket_mediano: Mapped[float] = mapped_column(Float, nullable=False)
    desconto_total: Mapped[float] = mapped_column(Float, nullable=False)
    percentual_pedidos_com_desconto: Mapped[float] = mapped_column(Float, nullable=False)
    percentual_pedidos_com_cupom: Mapped[float] = mapped_column(Float, nullable=False)
    itens_por_pedido: Mapped[float] = mapped_column(Float, nullable=False)
    margem_media: Mapped[float] = mapped_column(Float, nullable=False)
    quantidade_pedidos_com_cupom: Mapped[float] = mapped_column(Float, nullable=False)
    prazo_medio_entrega: Mapped[float] = mapped_column(Float, nullable=False)
    atraso_medio_entrega: Mapped[float] = mapped_column(Float, nullable=False)
    maior_atraso_entrega: Mapped[float] = mapped_column(Float, nullable=False)
    pedidos_com_atraso: Mapped[float] = mapped_column(Float, nullable=False)
    percentual_pedidos_com_atraso: Mapped[float] = mapped_column(Float, nullable=False)
    meses_com_interacao: Mapped[float] = mapped_column(Float, nullable=False)
    campanhas_enviadas_total: Mapped[float] = mapped_column(Float, nullable=False)
    campanhas_reativacao_total: Mapped[float] = mapped_column(Float, nullable=False)
    campanhas_abertas_total: Mapped[float] = mapped_column(Float, nullable=False)
    cliques_total: Mapped[float] = mapped_column(Float, nullable=False)
    sessoes_total: Mapped[float] = mapped_column(Float, nullable=False)
    carrinhos_abandonados_total: Mapped[float] = mapped_column(Float, nullable=False)
    tickets_sac_total: Mapped[float] = mapped_column(Float, nullable=False)
    tickets_resolvidos_total: Mapped[float] = mapped_column(Float, nullable=False)
    taxa_abertura_campanhas: Mapped[float] = mapped_column(Float, nullable=False)
    taxa_clique_campanhas: Mapped[float] = mapped_column(Float, nullable=False)
    taxa_resolucao_sac: Mapped[float] = mapped_column(Float, nullable=False)
    campanhas_reativacao_por_campanha: Mapped[float] = mapped_column(Float, nullable=False)
    cliques_por_campanha_aberta: Mapped[float] = mapped_column(Float, nullable=False)
    sessoes_por_pedido: Mapped[float] = mapped_column(Float, nullable=False)
    tickets_por_pedido: Mapped[float] = mapped_column(Float, nullable=False)
    carrinhos_por_sessao: Mapped[float] = mapped_column(Float, nullable=False)
    sem_interacao: Mapped[float] = mapped_column(Float, nullable=False)


class DesviosCluster(Base):
    __tablename__ = "desvios_cluster"

    cluster: Mapped[int] = mapped_column(Integer, primary_key=True)
    atributo: Mapped[str] = mapped_column(String, primary_key=True)
    desvio_padrao: Mapped[float] = mapped_column(Float, nullable=False)
    quantidade_clusters: Mapped[int] = mapped_column(Integer, nullable=False)
    data_referencia: Mapped[date] = mapped_column(Date, nullable=False)
    data_geracao: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    versao_atributos: Mapped[str] = mapped_column(String, nullable=False)
